### PR TITLE
Setup view

### PR DESCRIPTION
**Pull request by anyepeter**
In this PR, I implemented the UI design and fetched data from the database with the following requirements 🔖; 

### General requirements
✅ Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
✅ Make sure that you have used correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
✅ Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
### Ruby requirements
✅ Follow our list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).
### Project requirements
✅ Implement the design from the sneak peek wireframes.
✅ Styling is nice to have but focus on making sure everything functions first. (Note: Ignore login logic, you would be using Devise in coming milestone)
✅ All Users page wireframe Single User page wireframe All Posts by a given User page wireframe Single Post page wireframe

✅ Use methods that you have created in the [Blog App - processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).
Hint: In order to see some posts or comments, you might need to add some data to your database as described [here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md#use-models-to-insert-data).

page1
page2
page3
page4

### CODE REVIEW

**Review by youmari — APPROVED** [review]
@anyepeter sorry for that it was a mistake

**Review by Ismailco — CHANGES_REQUESTED** [review]
### Hi @anyepeter, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ Create Views
✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Required Changes ♻️
- [ ] Kindly make sure to fix your migration files, I can't create the database because some tables/columns are removed before being created and some are used in other tables as references while they are not created yet.

Screenshot_20230309_131359

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by anyepeter** [comment]
Hello @Ismailco,
Actually I don't know exactly what you meant by I should fix my migration. Please can you help me out?

**Comment by anyepeter** [comment]
Hello code reviewer 😁👋, 
In my schema file, my database is setup properly as required and without the AuthorId. I used this command to install the database into another PC "db:schema:load"  and everything works well.

**Comment by Ismailco** [comment]
@anyepeter, ok `db:shema:load` will work because the schema file in your project is created with old migrations, if you drop the database and did `db:migrate` you will get an error. to fix it you should check the migration files and fix any issues there or use the same migration files that created the schema file

**Comment by anyepeter** [comment]
@Ismailco, means I should remove my migration files or how?

**Review by ShadyShawkat — APPROVED** [review]
## Hi @anyepeter, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by anyepeter** [comment]
@ShadyShawkat Thank you very much for approving my project.

**Pull request merged**
